import Head from 'next/head'
import Image from 'next/image'
import Navbar from './navbar'
import Footer from './footer'
import bg from '../assets/home-bg.png'
import layoutCss from '../styles/components/layout.module.css'
import 'animate.css';


export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Alders Antonius Samosir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        backgroundImage: `url(${bg.src})`
      }} 
      className={layoutCss.main_banner}>
        <div className={layoutCss.bg_drop}>
        <Navbar />
        <main className='animate__fadeInLeft'>{children}</main>
        <Footer />
        </div>
      </div>
    </>
  )
}