import Document, {Head, Main, NextScript, title} from 'next/document'
import {Manifest} from 'next-manifest';


export default class extends Document {

  render() {
    return (
      <html lang="en">
        <Head>
        <title>Alders Antonius Samosir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Manifest href="/static/manifest.json"/>
        <link rel="stylesheet" media="all and (orientation:portrait)" href="portrait.css"/>

        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
